name: tune_your_headphones
description: Stwórz swoją krzywą strojenia słuchawek

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  audioplayers: ^1.0.1
  provider: ^6.0.3
  path_provider: ^2.0.11
  permission_handler: ^10.0.1
  awesome_notifications: ^0.6.21
  font_awesome_flutter: ^10.2.1
  flutter_launcher_icons: ^0.10.0
  url_launcher: ^6.1.5
  #http: ^0.13.4
  #js: ^0.6.3

flutter_icons:
  image_path: "assets/pictures/icon192.png"
  android: true

  adaptive_icon_background: "assets/pictures/icon.png"
  adaptive_icon_foreground: "assets/pictures/icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/30/
    - assets/pictures/

