name: tune_your_headphones
description: Stwórz swoją krzywą strojenia słuchawek

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audioplayers: ^0.20.1
  provider: ^6.0.2
  permission_handler: ^9.2.0
  awesome_notifications: ^0.6.21
  font_awesome_flutter: ^10.1.0
  flutter_launcher_icons: ^0.9.3
  http: ^0.13.4
  js: ^0.6.3

flutter_icons:
  image_path: "pictures/icon.bmp"
  android: true
  ios: true
  remove_alpha_ios: true

  adaptive_icon_background: "pictures/icon.bmp"
  adaptive_icon_foreground: "pictures/icon.bmp"


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/30/
    - assets/pictures/

